/**
 * Descriptor Tables - Core Mythic GME v2 Oracles
 * Used to generate descriptive details for characters, objects, and situations
 */

import { OracleTable, OracleType, DiceType } from '../../types';

/**
 * Character Descriptors - Describe NPCs and characters
 */
export const characterDescriptorTable: OracleTable = {
  id: 'descriptor-character',
  name: 'Character Descriptor',
  category: 'Core Mythic GME v2',
  type: OracleType.DESCRIPTOR,
  diceType: DiceType.D100,
  description: 'Generate descriptive traits for characters',
  entries: [
    { range: [1, 1], result: 'Abnormally' },
    { range: [2, 2], result: 'Adventurously' },
    { range: [3, 3], result: 'Aggressively' },
    { range: [4, 4], result: 'Angrily' },
    { range: [5, 5], result: 'Anxiously' },
    { range: [6, 6], result: 'Awkwardly' },
    { range: [7, 7], result: 'Beautifully' },
    { range: [8, 8], result: 'Bleakly' },
    { range: [9, 9], result: 'Boldly' },
    { range: [10, 10], result: 'Bravely' },
    { range: [11, 11], result: 'Busily' },
    { range: [12, 12], result: 'Calmly' },
    { range: [13, 13], result: 'Carefully' },
    { range: [14, 14], result: 'Carelessly' },
    { range: [15, 15], result: 'Cautiously' },
    { range: [16, 16], result: 'Cheerfully' },
    { range: [17, 17], result: 'Cleverly' },
    { range: [18, 18], result: 'Cluelessly' },
    { range: [19, 19], result: 'Clumsily' },
    { range: [20, 20], result: 'Colorfully' },
    { range: [21, 21], result: 'Combatively' },
    { range: [22, 22], result: 'Coolly' },
    { range: [23, 23], result: 'Courageously' },
    { range: [24, 24], result: 'Crazily' },
    { range: [25, 25], result: 'Creatively' },
    { range: [26, 26], result: 'Cruelly' },
    { range: [27, 27], result: 'Curiously' },
    { range: [28, 28], result: 'Daintily' },
    { range: [29, 29], result: 'Dangerously' },
    { range: [30, 30], result: 'Defiantly' },
    { range: [31, 31], result: 'Deliberately' },
    { range: [32, 32], result: 'Delightfully' },
    { range: [33, 33], result: 'Dimly' },
    { range: [34, 34], result: 'Efficiently' },
    { range: [35, 35], result: 'Energetically' },
    { range: [36, 36], result: 'Enormously' },
    { range: [37, 37], result: 'Enthusiastically' },
    { range: [38, 38], result: 'Excitedly' },
    { range: [39, 39], result: 'Fearfully' },
    { range: [40, 40], result: 'Ferociously' },
    { range: [41, 41], result: 'Fiercely' },
    { range: [42, 42], result: 'Foolishly' },
    { range: [43, 43], result: 'Fortunately' },
    { range: [44, 44], result: 'Frantically' },
    { range: [45, 45], result: 'Freely' },
    { range: [46, 46], result: 'Frighteningly' },
    { range: [47, 47], result: 'Fully' },
    { range: [48, 48], result: 'Generously' },
    { range: [49, 49], result: 'Gently' },
    { range: [50, 50], result: 'Gladly' },
    { range: [51, 51], result: 'Gracefully' },
    { range: [52, 52], result: 'Gratefully' },
    { range: [53, 53], result: 'Happily' },
    { range: [54, 54], result: 'Hastily' },
    { range: [55, 55], result: 'Healthily' },
    { range: [56, 56], result: 'Helpfully' },
    { range: [57, 57], result: 'Helplessly' },
    { range: [58, 58], result: 'Hopelessly' },
    { range: [59, 59], result: 'Innocently' },
    { range: [60, 60], result: 'Intensely' },
    { range: [61, 61], result: 'Interestingly' },
    { range: [62, 62], result: 'Intimidatingly' },
    { range: [63, 63], result: 'Jovially' },
    { range: [64, 64], result: 'Joyfully' },
    { range: [65, 65], result: 'Judgementally' },
    { range: [66, 66], result: 'Kindly' },
    { range: [67, 67], result: 'Knavishly' },
    { range: [68, 68], result: 'Lazily' },
    { range: [69, 69], result: 'Lightly' },
    { range: [70, 70], result: 'Loosely' },
    { range: [71, 71], result: 'Loudly' },
    { range: [72, 72], result: 'Lovingly' },
    { range: [73, 73], result: 'Loyally' },
    { range: [74, 74], result: 'Majestically' },
    { range: [75, 75], result: 'Meaningfully' },
    { range: [76, 76], result: 'Mechanically' },
    { range: [77, 77], result: 'Miserably' },
    { range: [78, 78], result: 'Mockingly' },
    { range: [79, 79], result: 'Mysteriously' },
    { range: [80, 80], result: 'Naturally' },
    { range: [81, 81], result: 'Neatly' },
    { range: [82, 82], result: 'Nicely' },
    { range: [83, 83], result: 'Oddly' },
    { range: [84, 84], result: 'Offensively' },
    { range: [85, 85], result: 'Officially' },
    { range: [86, 86], result: 'Partially' },
    { range: [87, 87], result: 'Peacefully' },
    { range: [88, 88], result: 'Perfectly' },
    { range: [89, 89], result: 'Playfully' },
    { range: [90, 90], result: 'Politely' },
    { range: [91, 91], result: 'Positively' },
    { range: [92, 92], result: 'Powerfully' },
    { range: [93, 93], result: 'Quaintly' },
    { range: [94, 94], result: 'Quarrelsomely' },
    { range: [95, 95], result: 'Quietly' },
    { range: [96, 96], result: 'Roughly' },
    { range: [97, 97], result: 'Rudely' },
    { range: [98, 98], result: 'Ruthlessly' },
    { range: [99, 99], result: 'Slowly' },
    { range: [100, 100], result: 'Swiftly' }
  ]
};

/**
 * Object Descriptors - Describe items and objects
 */
export const objectDescriptorTable: OracleTable = {
  id: 'descriptor-object',
  name: 'Object Descriptor',
  category: 'Core Mythic GME v2',
  type: OracleType.DESCRIPTOR,
  diceType: DiceType.D100,
  description: 'Generate descriptive traits for objects and items',
  entries: [
    { range: [1, 1], result: 'Abandoned' },
    { range: [2, 2], result: 'Abnormal' },
    { range: [3, 3], result: 'Amusing' },
    { range: [4, 4], result: 'Ancient' },
    { range: [5, 5], result: 'Aromatic' },
    { range: [6, 6], result: 'Average' },
    { range: [7, 7], result: 'Beautiful' },
    { range: [8, 8], result: 'Bizarre' },
    { range: [9, 9], result: 'Classy' },
    { range: [10, 10], result: 'Clean' },
    { range: [11, 11], result: 'Cold' },
    { range: [12, 12], result: 'Colorful' },
    { range: [13, 13], result: 'Creepy' },
    { range: [14, 14], result: 'Cute' },
    { range: [15, 15], result: 'Damaged' },
    { range: [16, 16], result: 'Dark' },
    { range: [17, 17], result: 'Defeated' },
    { range: [18, 18], result: 'Delicate' },
    { range: [19, 19], result: 'Delightful' },
    { range: [20, 20], result: 'Dirty' },
    { range: [21, 21], result: 'Disagreeable' },
    { range: [22, 22], result: 'Disgusting' },
    { range: [23, 23], result: 'Drab' },
    { range: [24, 24], result: 'Dry' },
    { range: [25, 25], result: 'Dull' },
    { range: [26, 26], result: 'Empty' },
    { range: [27, 27], result: 'Enormous' },
    { range: [28, 28], result: 'Exotic' },
    { range: [29, 29], result: 'Faded' },
    { range: [30, 30], result: 'Familiar' },
    { range: [31, 31], result: 'Fancy' },
    { range: [32, 32], result: 'Fat' },
    { range: [33, 33], result: 'Feeble' },
    { range: [34, 34], result: 'Feminine' },
    { range: [35, 35], result: 'Festive' },
    { range: [36, 36], result: 'Flawless' },
    { range: [37, 37], result: 'Fresh' },
    { range: [38, 38], result: 'Full' },
    { range: [39, 39], result: 'Glorious' },
    { range: [40, 40], result: 'Good' },
    { range: [41, 41], result: 'Graceful' },
    { range: [42, 42], result: 'Hard' },
    { range: [43, 43], result: 'Harsh' },
    { range: [44, 44], result: 'Healthy' },
    { range: [45, 45], result: 'Heavy' },
    { range: [46, 46], result: 'Historical' },
    { range: [47, 47], result: 'Horrible' },
    { range: [48, 48], result: 'Important' },
    { range: [49, 49], result: 'Interesting' },
    { range: [50, 50], result: 'Juvenile' },
    { range: [51, 51], result: 'Lacking' },
    { range: [52, 52], result: 'Lame' },
    { range: [53, 53], result: 'Large' },
    { range: [54, 54], result: 'Lavish' },
    { range: [55, 55], result: 'Lean' },
    { range: [56, 56], result: 'Less' },
    { range: [57, 57], result: 'Light' },
    { range: [58, 58], result: 'Lovely' },
    { range: [59, 59], result: 'Macabre' },
    { range: [60, 60], result: 'Magnificent' },
    { range: [61, 61], result: 'Masculine' },
    { range: [62, 62], result: 'Mature' },
    { range: [63, 63], result: 'Messy' },
    { range: [64, 64], result: 'Mighty' },
    { range: [65, 65], result: 'Military' },
    { range: [66, 66], result: 'Modern' },
    { range: [67, 67], result: 'Extravagant' },
    { range: [68, 68], result: 'Mundane' },
    { range: [69, 69], result: 'Mysterious' },
    { range: [70, 70], result: 'Natural' },
    { range: [71, 71], result: 'Nondescript' },
    { range: [72, 72], result: 'Odd' },
    { range: [73, 73], result: 'Pale' },
    { range: [74, 74], result: 'Petite' },
    { range: [75, 75], result: 'Poor' },
    { range: [76, 76], result: 'Powerful' },
    { range: [77, 77], result: 'Quaint' },
    { range: [78, 78], result: 'Rare' },
    { range: [79, 79], result: 'Reassuring' },
    { range: [80, 80], result: 'Remarkable' },
    { range: [81, 81], result: 'Rotten' },
    { range: [82, 82], result: 'Rough' },
    { range: [83, 83], result: 'Ruined' },
    { range: [84, 84], result: 'Rustic' },
    { range: [85, 85], result: 'Scary' },
    { range: [86, 86], result: 'Simple' },
    { range: [87, 87], result: 'Small' },
    { range: [88, 88], result: 'Smelly' },
    { range: [89, 89], result: 'Smooth' },
    { range: [90, 90], result: 'Soft' },
    { range: [91, 91], result: 'Strong' },
    { range: [92, 92], result: 'Tranquil' },
    { range: [93, 93], result: 'Ugly' },
    { range: [94, 94], result: 'Valuable' },
    { range: [95, 95], result: 'Warlike' },
    { range: [96, 96], result: 'Warm' },
    { range: [97, 97], result: 'Watery' },
    { range: [98, 98], result: 'Weak' },
    { range: [99, 99], result: 'Young' },
    { range: [100, 100], result: 'Unusual' }
  ]
};
