/**
 * Event Meaning Tables - Core Mythic GME v2 Oracles
 * Used to generate random scene events by combining Action and Description
 */

import { OracleTable, OracleType, DiceType } from '../../types';

/**
 * Action Table - 100 action words for event generation
 */
export const actionTable: OracleTable = {
  id: 'event-meaning-action',
  name: 'Action',
  category: 'Core Mythic GME v2',
  type: OracleType.STANDARD,
  diceType: DiceType.D100,
  description: 'Action component for Event Meaning',
  entries: [
    { range: [1, 1], result: 'Attainment' },
    { range: [2, 2], result: 'Starting' },
    { range: [3, 3], result: 'Neglect' },
    { range: [4, 4], result: 'Fight' },
    { range: [5, 5], result: 'Recruit' },
    { range: [6, 6], result: 'Triumph' },
    { range: [7, 7], result: 'Violate' },
    { range: [8, 8], result: 'Oppose' },
    { range: [9, 9], result: 'Malice' },
    { range: [10, 10], result: 'Communicate' },
    { range: [11, 11], result: 'Persecute' },
    { range: [12, 12], result: 'Increase' },
    { range: [13, 13], result: 'Decrease' },
    { range: [14, 14], result: 'Abandon' },
    { range: [15, 15], result: 'Gratify' },
    { range: [16, 16], result: 'Inquire' },
    { range: [17, 17], result: 'Antagonise' },
    { range: [18, 18], result: 'Move' },
    { range: [19, 19], result: 'Waste' },
    { range: [20, 20], result: 'Truce' },
    { range: [21, 21], result: 'Release' },
    { range: [22, 22], result: 'Befriend' },
    { range: [23, 23], result: 'Judge' },
    { range: [24, 24], result: 'Desert' },
    { range: [25, 25], result: 'Dominate' },
    { range: [26, 26], result: 'Procrastinate' },
    { range: [27, 27], result: 'Praise' },
    { range: [28, 28], result: 'Separate' },
    { range: [29, 29], result: 'Take' },
    { range: [30, 30], result: 'Break' },
    { range: [31, 31], result: 'Heal' },
    { range: [32, 32], result: 'Delay' },
    { range: [33, 33], result: 'Stop' },
    { range: [34, 34], result: 'Lie' },
    { range: [35, 35], result: 'Return' },
    { range: [36, 36], result: 'Imitate' },
    { range: [37, 37], result: 'Struggle' },
    { range: [38, 38], result: 'Inform' },
    { range: [39, 39], result: 'Bestow' },
    { range: [40, 40], result: 'Postpone' },
    { range: [41, 41], result: 'Expose' },
    { range: [42, 42], result: 'Haggle' },
    { range: [43, 43], result: 'Entrap' },
    { range: [44, 44], result: 'Abuse' },
    { range: [45, 45], result: 'Oppress' },
    { range: [46, 46], result: 'Inspect' },
    { range: [47, 47], result: 'Ambush' },
    { range: [48, 48], result: 'Spy' },
    { range: [49, 49], result: 'Attach' },
    { range: [50, 50], result: 'Carry' },
    { range: [51, 51], result: 'Open' },
    { range: [52, 52], result: 'Carelessness' },
    { range: [53, 53], result: 'Ruin' },
    { range: [54, 54], result: 'Extravagance' },
    { range: [55, 55], result: 'Trick' },
    { range: [56, 56], result: 'Arrive' },
    { range: [57, 57], result: 'Propose' },
    { range: [58, 58], result: 'Divide' },
    { range: [59, 59], result: 'Refuse' },
    { range: [60, 60], result: 'Betray' },
    { range: [61, 61], result: 'Depart' },
    { range: [62, 62], result: 'Deceive' },
    { range: [63, 63], result: 'Cruelty' },
    { range: [64, 64], result: 'Intolerance' },
    { range: [65, 65], result: 'Trust' },
    { range: [66, 66], result: 'Excitement' },
    { range: [67, 67], result: 'Activity' },
    { range: [68, 68], result: 'Assist' },
    { range: [69, 69], result: 'Care' },
    { range: [70, 70], result: 'Negligence' },
    { range: [71, 71], result: 'Passion' },
    { range: [72, 72], result: 'Work' },
    { range: [73, 73], result: 'Control' },
    { range: [74, 74], result: 'Attract' },
    { range: [75, 75], result: 'Failure' },
    { range: [76, 76], result: 'Pursue' },
    { range: [77, 77], result: 'Vengeance' },
    { range: [78, 78], result: 'Proceedings' },
    { range: [79, 79], result: 'Dispute' },
    { range: [80, 80], result: 'Punish' },
    { range: [81, 81], result: 'Guide' },
    { range: [82, 82], result: 'Transform' },
    { range: [83, 83], result: 'Overthrow' },
    { range: [84, 84], result: 'Oppress' },
    { range: [85, 85], result: 'Change' },
    { range: [86, 86], result: 'Release' },
    { range: [87, 87], result: 'Befriend' },
    { range: [88, 88], result: 'Judge' },
    { range: [89, 89], result: 'Desert' },
    { range: [90, 90], result: 'Dominate' },
    { range: [91, 91], result: 'Procrastinate' },
    { range: [92, 92], result: 'Praise' },
    { range: [93, 93], result: 'Separate' },
    { range: [94, 94], result: 'Take' },
    { range: [95, 95], result: 'Break' },
    { range: [96, 96], result: 'Heal' },
    { range: [97, 97], result: 'Delay' },
    { range: [98, 98], result: 'Stop' },
    { range: [99, 99], result: 'Lie' },
    { range: [100, 100], result: 'Return' }
  ]
};

/**
 * Description Table - 100 descriptive words for event generation
 */
export const descriptionTable: OracleTable = {
  id: 'event-meaning-description',
  name: 'Description',
  category: 'Core Mythic GME v2',
  type: OracleType.STANDARD,
  diceType: DiceType.D100,
  description: 'Description component for Event Meaning',
  entries: [
    { range: [1, 1], result: 'Goals' },
    { range: [2, 2], result: 'Dreams' },
    { range: [3, 3], result: 'Environment' },
    { range: [4, 4], result: 'Outside' },
    { range: [5, 5], result: 'Inside' },
    { range: [6, 6], result: 'Reality' },
    { range: [7, 7], result: 'Allies' },
    { range: [8, 8], result: 'Enemies' },
    { range: [9, 9], result: 'Evil' },
    { range: [10, 10], result: 'Good' },
    { range: [11, 11], result: 'Emotions' },
    { range: [12, 12], result: 'Opposition' },
    { range: [13, 13], result: 'War' },
    { range: [14, 14], result: 'Peace' },
    { range: [15, 15], result: 'Innocent' },
    { range: [16, 16], result: 'Love' },
    { range: [17, 17], result: 'Spirit' },
    { range: [18, 18], result: 'Intellect' },
    { range: [19, 19], result: 'Ideas' },
    { range: [20, 20], result: 'Joy' },
    { range: [21, 21], result: 'Messages' },
    { range: [22, 22], result: 'Energy' },
    { range: [23, 23], result: 'Balance' },
    { range: [24, 24], result: 'Tension' },
    { range: [25, 25], result: 'Friendship' },
    { range: [26, 26], result: 'Physical' },
    { range: [27, 27], result: 'Project' },
    { range: [28, 28], result: 'Pleasures' },
    { range: [29, 29], result: 'Pain' },
    { range: [30, 30], result: 'Possessions' },
    { range: [31, 31], result: 'Benefits' },
    { range: [32, 32], result: 'Plans' },
    { range: [33, 33], result: 'Lies' },
    { range: [34, 34], result: 'Expectations' },
    { range: [35, 35], result: 'Legal' },
    { range: [36, 36], result: 'Bureaucracy' },
    { range: [37, 37], result: 'Business' },
    { range: [38, 38], result: 'Path' },
    { range: [39, 39], result: 'News' },
    { range: [40, 40], result: 'Exterior Factors' },
    { range: [41, 41], result: 'Advice' },
    { range: [42, 42], result: 'Plot' },
    { range: [43, 43], result: 'Competition' },
    { range: [44, 44], result: 'Prison' },
    { range: [45, 45], result: 'Illness' },
    { range: [46, 46], result: 'Food' },
    { range: [47, 47], result: 'Attention' },
    { range: [48, 48], result: 'Success' },
    { range: [49, 49], result: 'Failure' },
    { range: [50, 50], result: 'Travel' },
    { range: [51, 51], result: 'Jealousy' },
    { range: [52, 52], result: 'Dispute' },
    { range: [53, 53], result: 'Home' },
    { range: [54, 54], result: 'Investment' },
    { range: [55, 55], result: 'Suffering' },
    { range: [56, 56], result: 'Wishes' },
    { range: [57, 57], result: 'Tactics' },
    { range: [58, 58], result: 'Stalemate' },
    { range: [59, 59], result: 'Randomness' },
    { range: [60, 60], result: 'Misfortune' },
    { range: [61, 61], result: 'Death' },
    { range: [62, 62], result: 'Disruption' },
    { range: [63, 63], result: 'Power' },
    { range: [64, 64], result: 'Burden' },
    { range: [65, 65], result: 'Intrigues' },
    { range: [66, 66], result: 'Fears' },
    { range: [67, 67], result: 'Ambush' },
    { range: [68, 68], result: 'Rumor' },
    { range: [69, 69], result: 'Wounds' },
    { range: [70, 70], result: 'Extravagance' },
    { range: [71, 71], result: 'Representative' },
    { range: [72, 72], result: 'Adversities' },
    { range: [73, 73], result: 'Opulence' },
    { range: [74, 74], result: 'Liberty' },
    { range: [75, 75], result: 'Military' },
    { range: [76, 76], result: 'Mundane' },
    { range: [77, 77], result: 'Trials' },
    { range: [78, 78], result: 'Masses' },
    { range: [79, 79], result: 'Vehicle' },
    { range: [80, 80], result: 'Art' },
    { range: [81, 81], result: 'Victory' },
    { range: [82, 82], result: 'Dispute' },
    { range: [83, 83], result: 'Riches' },
    { range: [84, 84], result: 'Status Quo' },
    { range: [85, 85], result: 'Technology' },
    { range: [86, 86], result: 'Hope' },
    { range: [87, 87], result: 'Magic' },
    { range: [88, 88], result: 'Illusions' },
    { range: [89, 89], result: 'Portals' },
    { range: [90, 90], result: 'Danger' },
    { range: [91, 91], result: 'Weapons' },
    { range: [92, 92], result: 'Animals' },
    { range: [93, 93], result: 'Weather' },
    { range: [94, 94], result: 'Elements' },
    { range: [95, 95], result: 'Nature' },
    { range: [96, 96], result: 'Masses' },
    { range: [97, 97], result: 'Leadership' },
    { range: [98, 98], result: 'Fame' },
    { range: [99, 99], result: 'Anger' },
    { range: [100, 100], result: 'Information' }
  ]
};
